#!/bin/bash
# ============================================================================
# SALFANET RADIUS — Application Setup (Monorepo)
# ============================================================================
# Clones repo, installs pnpm deps, builds frontend + backend,
# runs Prisma migrations, creates .env files.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# ============================================================================
# CLONE OR UPDATE REPO
# ============================================================================

clone_repo() {
    print_step "Clone/Update Application"

    if [ -d "$APP_DIR/.git" ]; then
        print_info "App directory exists — pulling latest..."
        cd "$APP_DIR"
        git pull origin "$GITHUB_BRANCH" || print_warn "git pull failed — continuing with existing code"
    else
        print_info "Cloning from GitHub..."
        rm -rf "$APP_DIR"
        git clone --branch "$GITHUB_BRANCH" "$GITHUB_REPO" "$APP_DIR"
        cd "$APP_DIR"
    fi

    print_success "Application code ready at $APP_DIR"
}

# ============================================================================
# INSTALL DEPENDENCIES
# ============================================================================

install_deps() {
    print_step "Install Dependencies (pnpm workspace)"

    cd "$APP_DIR" || die "App directory not found"

    # Install workspace deps
    pnpm install --no-frozen-lockfile || die "pnpm install failed"

    # Build shared-types first (frontend + backend depend on it)
    print_info "Building @salfanet/shared-types..."
    pnpm --filter @salfanet/shared-types build || die "shared-types build failed"

    print_success "Dependencies installed"
}

# ============================================================================
# GENERATE .env FILES
# ============================================================================

generate_env() {
    print_step "Generate .env Files"

    cd "$APP_DIR" || die

    local secret
    secret=$(generate_secret)

    local db_url="mysql://${DB_USER}:${DB_PASSWORD}@localhost:3306/${DB_NAME}?connection_limit=10&pool_timeout=20"

    # --- Root .env (shared) ---
    cat > .env <<EOF
# === Salfanet Radius — Root .env (generated by installer) ===
DATABASE_URL="${db_url}"
NEXTAUTH_SECRET="${secret}"
NEXTAUTH_URL="http://localhost:${FRONTEND_PORT}"
JWT_SECRET="$(generate_secret)"
AGENT_JWT_SECRET="$(generate_secret)"
TECH_JWT_SECRET="$(generate_secret)"
ENCRYPTION_KEY="$(generate_secret)"
TZ="${SYSTEM_TIMEZONE}"
EOF

    # --- Frontend .env ---
    cat > frontend/.env <<EOF
DATABASE_URL="${db_url}"
NEXTAUTH_SECRET="${secret}"
NEXTAUTH_URL="http://localhost:${FRONTEND_PORT}"
BACKEND_URL="http://127.0.0.1:${BACKEND_PORT}"
TZ="${SYSTEM_TIMEZONE}"
NEXT_PUBLIC_TIMEZONE="${SYSTEM_TIMEZONE}"
NEXT_PUBLIC_APP_NAME="Salfanet Radius"
NEXT_PUBLIC_APP_URL="http://localhost:${FRONTEND_PORT}"
NEXT_PUBLIC_API_URL="http://127.0.0.1:${BACKEND_PORT}"
EOF

    # --- Backend .env ---
    cat > backend/.env <<EOF
PORT=${BACKEND_PORT}
NODE_ENV=production
CORS_ORIGINS="http://localhost:${FRONTEND_PORT}"
DATABASE_URL="${db_url}"
NEXTAUTH_SECRET="${secret}"
NEXTAUTH_URL="http://localhost:${FRONTEND_PORT}"
AGENT_JWT_SECRET="$(generate_secret)"
TECH_JWT_SECRET="$(generate_secret)"
ENCRYPTION_KEY="$(generate_secret)"
FRONTEND_URL="http://localhost:${FRONTEND_PORT}"
FREERADIUS_CONFIG_DIR="/etc/freeradius/3.0"
FREERADIUS_SERVICE="freeradius"
WA_SERVICE_URL="http://127.0.0.1:${WA_PORT}"
TZ="${SYSTEM_TIMEZONE}"
EOF

    print_success ".env files generated (root, frontend, backend)"
}

# ============================================================================
# PRISMA MIGRATIONS + SEED
# ============================================================================

run_migrations() {
    print_step "Prisma Migrations + Database Seed"

    cd "$APP_DIR/frontend" || die "frontend directory not found"

    # Generate Prisma client
    pnpm exec prisma generate || die "prisma generate failed"

    # Run migrations
    pnpm exec prisma migrate deploy || {
        print_warn "prisma migrate deploy had issues — trying db push..."
        pnpm exec prisma db push --accept-data-loss || die "prisma db push failed"
    }

    # Run RADIUS enhancement SQL (radippool, cui, data_usage tables, SP)
    if [ -f "prisma/migrate-radius-enhancements.sql" ]; then
        print_info "Applying RADIUS enhancements SQL..."
        mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < prisma/migrate-radius-enhancements.sql 2>/dev/null || \
            print_warn "RADIUS enhancements SQL had issues (may already be applied)"
    fi

    # Import FreeRADIUS stored procedure
    if [ -f "$APP_DIR/deploy/freeradius/fr_allocate_sp.sql" ]; then
        print_info "Importing FreeRADIUS stored procedure..."
        mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" < "$APP_DIR/deploy/freeradius/fr_allocate_sp.sql" 2>/dev/null || \
            print_warn "SP import had issues (may already exist)"
    fi

    # Seed (optional — don't fail if seed has issues)
    print_info "Running database seed..."
    pnpm run db:seed 2>/dev/null || print_warn "Seed had issues — you can run manually later"

    print_success "Database migrations + seed complete"
}

# ============================================================================
# BUILD FRONTEND + BACKEND
# ============================================================================

build_app() {
    print_step "Build Frontend + Backend"

    cd "$APP_DIR" || die

    # Build shared-types (already built in install_deps, but ensure)
    pnpm --filter @salfanet/shared-types build 2>/dev/null || true

    # Build backend
    print_info "Building NestJS backend..."
    pnpm --filter backend build || die "Backend build failed"

    # Build frontend (needs NEXTAUTH_SECRET for production build)
    print_info "Building Next.js frontend..."
    cd frontend
    NEXTAUTH_SECRET="$(grep NEXTAUTH_SECRET ../.env | cut -d'"' -f2)" \
    DATABASE_URL="$(grep DATABASE_URL ../.env | cut -d'"' -f2)" \
    pnpm run build || die "Frontend build failed"

    # Copy .env to standalone (postbuild script does this, but ensure)
    if [ -f ".env" ] && [ -d ".next/standalone" ]; then
        cp .env .next/standalone/.env
    fi

    cd "$APP_DIR"
    print_success "Frontend + Backend built successfully"
}

# ============================================================================
# MAIN
# ============================================================================

install_app() {
    clone_repo
    install_deps
    generate_env
    run_migrations
    build_app
}
