packages:
  - 'frontend'
  - 'backend'
  - 'packages/*'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@whiskeysockets/baileys'
  - 'core-js'
  - 'cpu-features'
  - 'esbuild'
  - 'prisma'
  - 'protobufjs'
  - 'sharp'
  - 'ssh2'
  - 'unrs-resolver'
