# -*- text -*-
#
#  Write Chargeable-User-Identity to the database.
#  Configured for MySQL (Salfanet)
#
sql cuisql {
    driver = "rlm_sql_mysql"
    dialect = "mysql"

    # Connection info
    server = "localhost"
    port = 3306
    login = "salfanet_user"
    password = "salfanetradius123"
    radius_db = "salfanet_radius"

    # Table name
    cui_table = "cui"

    # SQL queries
    $INCLUDE ${modconfdir}/sql/cui/mysql/queries.conf
}
