import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, readFile } from 'fs/promises';

const execAsync = promisify(exec);

const NAS_CLIENTS_FILE = '/etc/freeradius/3.0/clients.d/nas-from-db.conf';

let lastRestartTime = 0;
const RESTART_COOLDOWN = 3000;

@Injectable()
export class FreeradiusService {
  private readonly logger = new Logger(FreeradiusService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Sync NAS entries from database to FreeRADIUS clients.d/nas-from-db.conf.
   * Ported from /server/services/radius/freeradius.service.ts.
   * Idempotent: only writes when content changed.
   */
  async syncNasClients(): Promise<boolean> {
    try {
      const nasEntries: Array<{
        nasname: string; ipAddress: string | null; shortname: string | null;
        secret: string; type: string | null; vpnClientId: string | null;
        vpnIp: string | null; isRadiusServer: boolean | null;
        vpnServerId: string | null; vpnServerName: string | null; vpnServerSubnet: string | null;
      }> = await this.prisma.$queryRaw`
        SELECT
          r.nasname, r.ipAddress, r.shortname, r.secret, r.type,
          r.vpnClientId, vc.vpnIp, vc.isRadiusServer,
          vs.id AS vpnServerId, vs.name AS vpnServerName, vs.subnet AS vpnServerSubnet
        FROM nas r
        LEFT JOIN vpn_clients vc ON vc.id = r.vpnClientId
        LEFT JOIN vpn_servers vs ON vs.id = vc.vpnServerId
        WHERE r.isActive = 1
      `;

      if (nasEntries.length === 0) return false;

      const lines: string[] = ['# Auto-generated by salfanet-radius - DO NOT EDIT MANUALLY', ''];

      const vpnGateways = new Map<string, { gatewayIp: string; secrets: Set<string>; serverName: string }>();

      for (const nas of nasEntries) {
        const safeShort = (nas.shortname || nas.nasname).replace(/[^a-z0-9_-]/gi, '_');
        lines.push(`client nas_${safeShort} {`);
        lines.push(`    ipaddr = ${nas.nasname}`);
        lines.push(`    secret = ${nas.secret}`);
        lines.push(`    shortname = ${safeShort}`);
        lines.push(`    nas_type = other`);
        lines.push(`    require_message_authenticator = no`);
        lines.push(`    limit_proxy_state = no`);
        lines.push(`}`);
        lines.push('');

        if (nas.vpnClientId && nas.vpnServerId && !nas.isRadiusServer) {
          if (!vpnGateways.has(nas.vpnServerId)) {
            const subnetBase = (nas.vpnServerSubnet || '').split('/')[0];
            const parts = subnetBase.split('.');
            parts[3] = '1';
            const gatewayIp = parts.join('.');
            const safeName = (nas.vpnServerName || nas.vpnServerId).replace(/[^a-z0-9_-]/gi, '_').toLowerCase();
            vpnGateways.set(nas.vpnServerId, { gatewayIp, secrets: new Set([nas.secret]), serverName: safeName });
          } else {
            vpnGateways.get(nas.vpnServerId)!.secrets.add(nas.secret);
          }
        }
      }

      if (vpnGateways.size > 0) {
        lines.push('# --- VPN Server Gateway Clients ---');
        lines.push('');
        for (const [, gw] of vpnGateways) {
          if (gw.secrets.size > 1) {
            this.logger.warn(`[FreeRADIUS] VPN gateway ${gw.gatewayIp} skipped: NAS secrets differ`);
            lines.push(`# SKIPPED: vpn_gw_${gw.serverName} — NAS secrets differ (${gw.secrets.size} unique secrets).`);
            lines.push('');
            continue;
          }
          const [secret] = gw.secrets;
          lines.push(`client vpn_gw_${gw.serverName} {`);
          lines.push(`    ipaddr = ${gw.gatewayIp}`);
          lines.push(`    secret = ${secret}`);
          lines.push(`    shortname = vpn_gw_${gw.serverName}`);
          lines.push(`    nas_type = other`);
          lines.push(`    require_message_authenticator = no`);
          lines.push(`    limit_proxy_state = no`);
          lines.push(`}`);
          lines.push('');
        }
      }

      const newContent = lines.join('\n');

      let currentContent = '';
      try {
        currentContent = await readFile(NAS_CLIENTS_FILE, 'utf8');
      } catch {
        // File doesn't exist yet
      }

      if (currentContent.trim() === newContent.trim()) {
        this.logger.log(`[FreeRADIUS] NAS config already in sync (${nasEntries.length} entries)`);
        return false;
      }

      await execAsync('mkdir -p /etc/freeradius/3.0/clients.d');
      await writeFile(NAS_CLIENTS_FILE, newContent, 'utf8');

      const { stdout: confContent } = await execAsync('cat /etc/freeradius/3.0/clients.conf').catch(() => ({ stdout: '' }));
      if (!confContent.includes('$INCLUDE clients.d/')) {
        await execAsync(`echo '\n$INCLUDE clients.d/' >> /etc/freeradius/3.0/clients.conf`);
      }

      this.logger.log(`[FreeRADIUS] NAS config updated (${nasEntries.length} entries, ${vpnGateways.size} VPN gateways) — reload required`);
      return true;
    } catch (error: any) {
      this.logger.error('[FreeRADIUS] Failed to sync NAS clients:', error.message);
      return false;
    }
  }

  /**
   * Restart FreeRADIUS service. Requires sudoers permission for PM2 user.
   * Ported from /server/services/radius/freeradius.service.ts.
   */
  async reloadFreeRadius(): Promise<{ success: boolean; message: string }> {
    const now = Date.now();
    if (now - lastRestartTime < RESTART_COOLDOWN) {
      return { success: true, message: 'FreeRADIUS restart skipped (cooldown active)' };
    }

    try {
      lastRestartTime = now;
      const configChanged = await this.syncNasClients();
      if (!configChanged) {
        return { success: true, message: 'Config unchanged, skipping restart' };
      }

      const { stderr } = await execAsync('systemctl restart freeradius', { timeout: 10000 });
      if (stderr) this.logger.error('FreeRADIUS restart stderr:', stderr);
      this.logger.log('FreeRADIUS restarted successfully');
      return { success: true, message: 'FreeRADIUS restarted successfully' };
    } catch (error: any) {
      this.logger.error('Failed to restart FreeRADIUS:', error.message);
      return { success: false, message: error.message };
    }
  }

  /**
   * Check if radclient is available (for CoA).
   */
  async isRadclientAvailable(): Promise<boolean> {
    try {
      await execAsync('which radclient', { timeout: 5000 });
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Send CoA disconnect via radclient — ported from coa-handler.service.
   */
  async sendCoADisconnect(params: {
    username: string;
    nasIpAddress: string;
    nasSecret: string;
    sessionId?: string;
    framedIp?: string;
  }): Promise<{ success: boolean; error?: string }> {
    const available = await this.isRadclientAvailable();
    if (!available) {
      return { success: false, error: 'radclient not installed' };
    }

    try {
      const attrs: string[] = [
        `NAS-IP-Address=${params.nasIpAddress}`,
        `User-Name=${params.username}`,
      ];
      if (params.framedIp) attrs.push(`Framed-IP-Address=${params.framedIp}`);
      if (params.sessionId) attrs.push(`Acct-Session-Id=${params.sessionId}`);

      // Write attributes to temp file
      const tmpFile = `/tmp/coa-${Date.now()}.attrs`;
      await writeFile(tmpFile, attrs.join('\n') + '\n');

      const { stdout, stderr } = await execAsync(
        `radclient -x ${params.nasIpAddress}:1700 disconnect ${params.nasSecret} -f ${tmpFile}`,
        { timeout: 10000 },
      );

      // Cleanup
      await execAsync(`rm -f ${tmpFile}`).catch(() => {});

      if (stderr && !stderr.includes('Received CoA-ACK')) {
        this.logger.warn(`[CoA] stderr: ${stderr}`);
      }

      return { success: true };
    } catch (error: any) {
      this.logger.error('[CoA] Disconnect failed:', error.message);
      return { success: false, error: error.message };
    }
  }
}
