import { type NextRequest, NextResponse } from 'next/server';
import { requirePermission } from '@/server/middleware/api-auth';
import { ok, fail } from '@/lib/genieacs/helpers';
import {
  getPresets,
  createOrUpdatePreset,
  getProvisions,
  createOrUpdateProvision,
} from '@/lib/genieacs/api-client';
import type { AutoProvisionConfig } from '@/lib/genieacs/types';

/**
 * GET /api/genieacs/auto-provision
 *   Returns the current auto-provision configuration assembled from
 *   the preset/provision pair that matches the naming convention
 *   "auto-provision-<channel>" or simply "auto-provision".
 *
 * POST /api/genieacs/auto-provision
 *   Applies the auto-provision config:
 *   1. Creates/replaces a provision script with the given actions.
 *   2. Creates/replaces a preset that calls that provision on inform.
 *
 * The approach intentionally uses NBI-only (no MongoDB) to keep
 * it compatible with remote GenieACS instances.
 */

const PROVISION_ID = 'auto-provision';
const PRESET_ID = 'auto-provision';

/** Build a JS provision script from the config actions */
function buildProvisionScript(config: AutoProvisionConfig): string {
  const lines: string[] = ['// Auto-provision script — generated by Salfanet Radius'];

  if (config.channel) {
    lines.push(`// Channel: ${config.channel}`);
  }
  lines.push('');

  if (config.setParameters && config.setParameters.length > 0) {
    lines.push('// Set parameters');
    for (const p of config.setParameters) {
      const val =
        typeof p.value === 'string' ? JSON.stringify(p.value) : String(p.value);
      const type = p.type ? `, ${JSON.stringify(p.type)}` : '';
      lines.push(`declare("${p.path}", {value: [${val}${type}]});`);
    }
    lines.push('');
  }

  if (config.additionalScript) {
    lines.push('// Custom script');
    lines.push(config.additionalScript);
    lines.push('');
  }

  return lines.join('\n');
}

export async function GET() {
  const auth = await requirePermission('settings.genieacs');
  if (!auth.authorized) return auth.response;

  try {
    const [presets, provisions] = await Promise.all([
      getPresets(),
      getProvisions(),
    ]);

    const preset = presets.find((p) => p._id === PRESET_ID) ?? null;
    const provision = provisions.find((p) => p._id === PROVISION_ID) ?? null;

    return ok({ preset, provision });
  } catch (e) {
    return fail((e as Error).message);
  }
}

export async function POST(req: NextRequest) {
  const auth = await requirePermission('settings.genieacs');
  if (!auth.authorized) return auth.response;

  try {
    const config: AutoProvisionConfig = await req.json();

    if (!config || typeof config !== 'object') {
      return fail('Invalid config body', 400);
    }

    const script = buildProvisionScript(config);

    // 1. Upsert provision script
    await createOrUpdateProvision(PROVISION_ID, script);

    // 2. Upsert preset that triggers the provision on every inform
    const presetBody = {
      weight: config.weight ?? 0,
      precondition: config.precondition ?? 'true',
      provisions: [[PROVISION_ID]],
      channel: config.channel ?? 'default',
    };
    await createOrUpdatePreset(PRESET_ID, presetBody);

    return ok({ provisionId: PROVISION_ID, presetId: PRESET_ID });
  } catch (e) {
    return fail((e as Error).message);
  }
}

export async function DELETE() {
  const auth = await requirePermission('settings.genieacs');
  if (!auth.authorized) return auth.response;

  try {
    // Import delete functions dynamically to avoid circular imports
    const { deletePreset, deleteProvision } = await import('@/lib/genieacs/api-client');
    await Promise.allSettled([
      deletePreset(PRESET_ID),
      deleteProvision(PROVISION_ID),
    ]);
    return ok({ deleted: true });
  } catch (e) {
    return fail((e as Error).message);
  }
}
